name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['7.4']
    name: 'PHPUnit - PHP/${{ matrix.php-version }} - OS/${{ matrix.os }}'
    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: example
        ports:
            - 3306
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: none
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Dependencies
        run: composer install --no-progress
      - name: Setup schema
        run: vendor/bin/doctrine orm:schema:update --force
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
      - name: PHPUnit
        run: php -dmemory_limit=-1 vendor/bin/phpunit
        env:
          BLACKBOX_DETAILED_PROPERTIES: 1
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['7.4']
    name: 'Coverage - PHP/${{ matrix.php-version }} - OS/${{ matrix.os }}'
    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: example
        ports:
            - 3306
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: xdebug
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Dependencies
        run: composer install --no-progress
      - name: Setup schema
        run: vendor/bin/doctrine orm:schema:update --force
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
      - name: PHPUnit
        run: php -dmemory_limit=-1 vendor/bin/phpunit --coverage-clover=coverage.clover
        env:
          BLACKBOX_SET_SIZE: 1
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4']
    name: 'Psalm - PHP/${{ matrix.php-version }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Dependencies
        run: composer install --no-progress
      - name: Psalm
        run: vendor/bin/psalm --shepherd
